
# See http://www.appveyor.com/docs/appveyor-yml for many more options
# Fron https://github.com/RamblingCookieMonster/PSStackExchange/blob/master/appveyor.yml
# Additional: https://dfinke.github.io/powershell/2018/01/23/PowerShell-Testing-Your-Scripts-For-v5-and-v6.html

environment:
  PSGalleryApiKey:
    secure: VGPEr3cXooAZfvnmzCzZ9i0i1Y2pc7BW2k0bWjCkV7WvD+0vKyiy+WwNH12rEdqc

skip_commits:
  message: /updated readme.*|update readme.*s/

build: false

test_script:
# Test with native PS version
  - pwsh: . .\build.ps1 -task Clean,Pester
  - ps: . .\build.ps1 -task Clean,Deploy

artifacts:
  - path: Release
    name: Release